name: Setup
description: Setup Python and Poetry environment, install dependencies, and set version

runs:
  using: composite
  steps:
    - name: Install poetry
      shell: bash
      run: pipx install poetry
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'poetry'
    - name: Install project dependencies
      if: steps.cached-venv.outputs.cache-hit != 'true'
      shell: bash
      run: poetry install --no-interaction --no-root
    - name: Set version string based on tag
      shell: bash
      run: .scripts/version.bash
